version: "3"

services:
  db:
    image: mysql:latest
    container_name: bkkroad
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 050819
    networks:
      - dev_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 050819
    networks:
      - dev_network

  adminer:
    depends_on:
      - db
    image: adminer:latest
    container_name: atlas
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  db_data:  

